In [2]:
from google.colab import files

uploaded = files.upload()

Saving train.csv to train.csv

In [3]:
import pandas as pd
df=pd.read_csv("train.csv")

In [4]:
import sqlite3

conn = sqlite3.connect("superstore.db")

df.to_sql("superstore", conn, if_exists="replace", index=False)

print("Table created successfully")

Table created successfully

In [5]:
pd.read_sql_query(
    "SELECT * FROM superstore LIMIT 5",
    conn
)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [6]:
pd.read_sql_query(
    """
    SELECT "Order ID", Sales
    FROM superstore
    LIMIT 10
    """,
    conn
)

         Order ID     Sales
0  CA-2017-152156  261.9600
1  CA-2017-152156  731.9400
2  CA-2017-138688   14.6200
3  US-2016-108966  957.5775
4  US-2016-108966   22.3680
5  CA-2015-115812   48.8600
6  CA-2015-115812    7.2800
7  CA-2015-115812  907.1520
8  CA-2015-115812   18.5040
9  CA-2015-115812  114.9000

In [7]:
#Find all orders where Sales is greater than 1,000. Show the Order ID, Product Name and Sales.”
pd.read_sql_query(
    """
    SELECT "Order ID", Sales,"Product Name"
    FROM superstore
    where Sales >=1000
    """,
    conn
)

,Order ID,Sales,Product Name
0,CA-2015-115812,1706.184,Chromcraft Rectangular Conference Tables
1,CA-2016-106320,1044.630,Bretford CR4500 Series Slim Rectangular Table
2,US-2016-150630,3083.430,"Riverside Palais Royal Lawyers Bookcase, Royal..."
3,CA-2017-117590,1097.544,GE 30524EE4
4,CA-2017-105816,1029.950,AT&T CL83451 4-Handset Telephone
...,...,...,...
457,CA-2015-114251,1080.096,Tennsco Double-Tier Lockers
458,CA-2016-117086,4404.900,"Riverside Palais Royal Lawyers Bookcase, Royal..."
459,CA-2017-146913,1403.920,Office Star - Professional Matrix Back Chair w...
460,CA-2015-169019,2177.584,GBC DocuBind P400 Electric Binding System
461,CA-2018-144491,1023.332,"Atlantic Metals Mobile 5-Shelf Bookcases, Cust..."

In [8]:
#Good. Now I want to know which products generated the highest sales. Give me the top 10 records with the highest Sales. Show Product Name, Category, and Sales.”
pd.read_sql_query("""
select "Product Name", Category,Sales
from superstore
ORDER BY Sales DESC
LIMIT 10


""",conn
)

,Product Name,Category,Sales
0,Cisco TelePresence System EX90 Videoconferenci...,Technology,22638.480
1,Canon imageCLASS 2200 Advanced Copier,Technology,17499.950
2,Canon imageCLASS 2200 Advanced Copier,Technology,13999.960
3,Canon imageCLASS 2200 Advanced Copier,Technology,11199.968
4,Canon imageCLASS 2200 Advanced Copier,Technology,10499.970
5,GBC Ibimaster 500 Manual ProClick Binding System,Office Supplies,9892.740
6,Ibico EPK-21 Electric Binding System,Office Supplies,9449.950
7,"3D Systems Cube Printer, 2nd Generation, Magenta",Technology,9099.930
8,HP Designjet T520 Inkjet Large Format Printer ...,Technology,8749.950
9,Canon imageCLASS 2200 Advanced Copier,Technology,8399.976

In [9]:
#Can you give me the total sales for each product category? I want to see which category is generating the most revenue.”
pd.read_sql_query(
    """
    select sum(sales),Category
    from superstore
    group by Category
    """,conn
)

    sum(sales)         Category
0  728658.5757        Furniture
1  705422.3340  Office Supplies
2  827455.8730       Technology

In [10]:
#Good. Now sort those categories from highest sales to lowest sales. I want the highest-performing category at the top.
pd.read_sql_query(
    """
    select category,sum(Sales) as total_sales
    from superstore
    group by category
    order by total_sales ASC

    """,conn
)

          Category  total_sales
0  Office Supplies  705422.3340
1        Furniture  728658.5757
2       Technology  827455.8730

In [11]:
#We know which category performs best. Now I want to know which individual products are driving those sales.
#Give me the top 10 products based on total sales. Show the Product Name and total sales.
pd.read_sql_query("""
SELECT "Product Name", SUM(Sales) AS Total_sales
FROM superstore
GROUP BY "Product Name"
ORDER BY Total_sales DESC
LIMIT 10
""", conn)

                                        Product Name  Total_sales
0              Canon imageCLASS 2200 Advanced Copier    61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2  Cisco TelePresence System EX90 Videoconferenci...    22638.480
3       HON 5400 Series Task Chairs for Big and Tall    21870.576
4         GBC DocuBind TL300 Electric Binding System    19823.479
5   GBC Ibimaster 500 Manual ProClick Binding System    19024.500
6               Hewlett Packard LaserJet 3310 Copier    18839.686
7  HP Designjet T520 Inkjet Large Format Printer ...    18374.895
8          GBC DocuBind P400 Electric Binding System    17965.068
9        High Speed Automatic Electric Letter Opener    17030.312

In [12]:
#Show me only the product categories whose total sales are greater than 700,000.
pd.read_sql_query(
    """
      select category ,sum(sales) as total_sales
      from superstore
      Group by category
      having sum(sales)>700000
    """,conn

)

          Category  total_sales
0        Furniture  728658.5757
1  Office Supplies  705422.3340
2       Technology  827455.8730

In [13]:
pd.read_sql_query("""
SELECT "Order ID", "Product Name", Category, Sales
FROM superstore
WHERE Category = 'Technology'
AND Sales > 1000
""", conn)

,Order ID,Product Name,Category,Sales
0,CA-2017-117590,GE 30524EE4,Technology,1097.544
1,CA-2017-105816,AT&T CL83451 4-Handset Telephone,Technology,1029.950
2,CA-2015-139892,Lexmark MX611dhe Monochrome Laser Printer,Technology,8159.952
3,CA-2016-146262,Cisco 9971 IP Video Phone Charcoal,Technology,1188.000
4,CA-2017-145625,Logitech P710e Mobile Speakerphone,Technology,3347.370
...,...,...,...,...
171,CA-2017-113607,Motorola L703CM,Technology,1091.930
172,CA-2017-125220,Plantronics CS510 - Over-the-Head monaural Wir...,Technology,1649.750
173,CA-2018-152975,Wilson SignalBoost 841262 DB PRO Amplifier Kit,Technology,1079.850
174,CA-2017-160717,Samsung Galaxy Mega 6.3,Technology,3023.928
175,CA-2017-114867,LG G2,Technology,1499.970

In [14]:
#For each region, tell me how many unique customers we have.
pd.read_sql_query("""SELECT Region, COUNT(DISTINCT "Customer ID") AS Unique_Customers
FROM superstore
GROUP BY Region""", conn)

    Region  Unique_Customers
0  Central               626
1     East               669
2    South               509
3     West               681

In [15]:
pd.read_sql_query("""
SELECT Category, AVG(Sales) AS Average_Sales
FROM superstore
GROUP BY Category
ORDER BY Average_Sales DESC;
""", conn)

          Category  Average_Sales
0       Technology     456.401474
1        Furniture     350.653790
2  Office Supplies     119.381001

In [16]:
#Classify every sales record as High, Medium, or Low based on Sales: above $1,000 = High, $100–$1,000 = Medium, below $100 = Low. Show the Sales amount and classification.”
pd.read_sql_query("""
SELECT
    Sales,
    CASE
        WHEN Sales > 1000 THEN 'High'
        WHEN Sales >= 100 THEN 'Medium'
        ELSE 'Low'
    END AS Sales_Level
FROM superstore;
""", conn)

         Sales Sales_Level
0     261.9600      Medium
1     731.9400      Medium
2      14.6200         Low
3     957.5775      Medium
4      22.3680         Low
...        ...         ...
9795    3.7980         Low
9796   10.3680         Low
9797  235.1880      Medium
9798   26.3760         Low
9799   10.3840         Low

[9800 rows x 2 columns]

In [ ]:
#Show me total sales for each year so we can understand our yearly performance
pd.read_sql_query("""
SELECT
    strftime('%Y', "Order Date") AS Year,
    SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Year
ORDER BY Year;
""", conn)
#SQLite uses strftime() for dates.

In [17]:
#Find all products whose total sales are higher than the average product's total sales.”
pd.read_sql_query("""
SELECT
    "Product Name",
    SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY "Product Name"
HAVING SUM(Sales) > (
    SELECT AVG(Product_Total)
    FROM (
        SELECT SUM(Sales) AS Product_Total
        FROM superstore
        GROUP BY "Product Name"
    )
)
ORDER BY Total_Sales DESC;
""", conn)

                                          Product Name  Total_Sales
0                Canon imageCLASS 2200 Advanced Copier    61599.824
1    Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2    Cisco TelePresence System EX90 Videoconferenci...    22638.480
3         HON 5400 Series Task Chairs for Big and Tall    21870.576
4           GBC DocuBind TL300 Electric Binding System    19823.479
..                                                 ...          ...
446                                 Maxell 4.7GB DVD-R     1231.692
447                                         Xerox 1888     1231.656
448                             Hon 4060 Series Tables     1231.560
449  Blue Parrot B250XT Professional Grade Wireless...     1229.836
450                Case Logic 2.4GHz Wireless Keyboard     1229.754

[451 rows x 2 columns]

In [18]:
#“Within each category, rank the products based on their total sales. I want to know the best-performing products within each category.”
pd.read_sql_query("""
SELECT
    Category,
    "Product Name",
    SUM(Sales) AS Total_Sales,
    RANK() OVER (
        PARTITION BY Category
        ORDER BY SUM(Sales) DESC
    ) AS Sales_Rank
FROM superstore
GROUP BY Category, "Product Name"
ORDER BY Category, Sales_Rank;
""", conn)

,Category,Product Name,Total_Sales,Sales_Rank
0,Furniture,HON 5400 Series Task Chairs for Big and Tall,21870.5760,1
1,Furniture,"Riverside Palais Royal Lawyers Bookcase, Royal...",15610.9656,2
2,Furniture,Bretford Rectangular Conference Table Tops,12995.2915,3
3,Furniture,Global Troy Executive Leather Low-Back Tilter,12975.3820,4
4,Furniture,SAFCO Arco Folding Chair,11572.7800,5
...,...,...,...,...
1844,Technology,Maxell CD-R Discs,15.7600,408
1845,Technology,Sannysis Cute Owl Design Soft Skin Case Cover ...,13.8600,409
1846,Technology,Memorex Mini Travel Drive 4 GB USB 2.0 Flash D...,13.6160,410
1847,Technology,Maxell 4.7GB DVD+R 5/Pack,11.6820,411
1848,Technology,PNY Rapid USB Car Charger - Black,9.5880,412